name: Day6 CI Test
on:
  push:
    branches: ["master","main"]
jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Run a test message
        run: echo "CI pipeline triggered successfully"
      
      
