name: Day6 CI Test
on:
  push:
    branches:
      -master
jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: action / checkout@v3
      
      - name: Run a test message
        run: echo "CI pip;eline triggered successfully"
      
      
